### ISSUE TITLE
Does the feature overlap with another feature

### ISSUE THREAD

**Issue by bkowshik** [mapbox/osm-compare#129]
- Per voice with @geohacker and @amishas157 
- Ref: https://github.com/mapbox/osm-compare/issues/112, https://github.com/mapbox/osm-compare/issues/108

---

As part of the [context based validation](https://github.com/mapbox/osm-compare/issues/112), this compare function will flag suspeciously overlapping features. A couple of examples we have seen in the recent past are:

- https://osmcha.mapbox.com/46963151/

<img width="1182" alt="screen shot 2017-03-30 at 10 59 17 am" src="https://cloud.githubusercontent.com/assets/2899501/24488954/ff5fb4de-1537-11e7-868d-6cf2d8ad3d5d.png">

*Lake in Manhattan overlapping existing buildings.*

- http://osmcha.mapbox.com/45536604/

<img width="1181" alt="screen shot 2017-03-30 at 11 02 32 am" src="https://cloud.githubusercontent.com/assets/2899501/24489017/6b2371b0-1538-11e7-8b7d-8d0d306a7c4e.png">

*A residential area becomes a Park for what looks like a Pokemon mapper.*

In scenario's like ^, the feature that was created/modified overlapped quite a lot of existing features on OpenStreetMap, which being the context of where the feature will actually be. It is super important to detect features like these and correct them as soon as possible as they affect the very looks of the map. Ex:

<img width="1227" alt="screen shot 2017-03-30 at 11 08 52 am" src="https://cloud.githubusercontent.com/assets/2899501/24489185/8126b728-1539-11e7-96b5-b1299ed554ba.png">

*Residential areas rendered as lake and park due to harmful edits.*

---

### Workflow

*NOTE: Focussing on just new/updated water bodies in iteration 1 to keep our focus narrow.*

1. A new lake or an existing lake gets edited on OpenStreetMap.
2. Calculate all map tiles (xyz) that cover the lake.
3. Download vector map tiles from Mapbox API, convert to a FeatureCollection with all features in the tile.
4. Check if new/modified lake overlaps with any feature in the FeatureCollection and flag if there is a *suspecious* overlap.

### Uncertainities
- What zoom level tiles should be downloaded from the API
    - Tile at lower zoom levels don't have all the data. Ex: Buildings generally show up in tiles greater than zoom 15
- There could be good overlaps too. We need to differentiate between a good and a harmful overlap.
- `Lakes` and `parks` features fit this use-case well. What other feature types can something like this handle?

---

cc: @planemad @manoharuss

**Comment by srividyacb** [comment]
Found two more cases where overlapping feature were bad edits

1. https://osmcha.mapbox.com/47340745/
2. https://osmcha.mapbox.com/47340745/

![image](https://cloud.githubusercontent.com/assets/3423533/24654852/31e1e2d6-1959-11e7-9ebf-08c22a538727.png)

**Comment by amishas157** [comment]
Working over this issue here: https://github.com/mapbox/osm-compare/pull/135. It's based on the workflow described by @bkowshik ^

Tracking down the issues which are coming by:
 - For relation type features, we get the bounding box of the relation and not the proper geometry. Therefore, we use individual relation members which are part of that relation to find any overlap with the existing features and also making sure it should not flag overlap members from the same relation

- Another issue which came by was closed ways geometry. So as these are not polygons , therefore it would be impossible to find feature with which it shares same osm area. To deal with that, we polygonized these kind of geometry in changeset-parser based on condition if it has id-area-key. [Ref](https://github.com/mapbox/real-changesets-parser/issues/1).

- Recently there was another issue of feature finding overlap with itself. And this is caused due to lag with a feature going to mapbox-streets and same feature coming this pipeline for processing. As if the formed happens early than the latter, then a feature would be flagged for overlapping with itself. To curb that from happening , we ignore the cases of feature overlapping with itself.

**Comment by bkowshik** [comment]
- http://osmcha.mapbox.com/47878397/
- A waterway created very close (almost touching) a highway.

<img width="1179" alt="screen shot 2017-04-22 at 2 52 42 pm" src="https://cloud.githubusercontent.com/assets/2899501/25303186/5e0947a8-276b-11e7-88c3-ac5f2d8990c9.png">

**Comment by amishas157** [comment]
Work in this PR : https://github.com/mapbox/osm-compare/pull/135
Closing the issue
